- group: { enabled: true, name: dollar }
- group: { enabled: true, name: future }
- group: { enabled: true, name: generalise }
- ignore: { name: Use list comprehension }
- ignore: { name: Use tuple-section }
- extensions:
    - default: false
    - name:
        - FlexibleContexts
        - RankNTypes
        - ScopedTypeVariables
        - TemplateHaskellQuotes
