- group: { enabled: true, name: dollar }
- group: { enabled: true, name: future }
- group: { enabled: true, name: generalise }
- ignore: { name: Use infix }
- ignore: { name: Use list comprehension }
- ignore: { name: Use tuple-section }
- extensions:
    - default: false
    - name:
        - DataKinds
        - DeriveGeneric
        - DerivingVia
        - FlexibleContexts
        - FlexibleInstances
        - MultilineStrings
        - RankNTypes
        - ScopedTypeVariables
        - StandaloneDeriving
        - TemplateHaskell
        - TemplateHaskellQuotes
        - TypeOperators
        - UndecidableInstances
