# https://docs.docker.com/reference/compose-file/
services:
  devcontainer:
    command: sleep infinity
    image: nixos/nix:2.33.1
    init: true
    volumes:
      - ..:/workspace
      - nix:/nix
    working_dir: /workspace
volumes:
  nix: null
