// Renders the footer section of a module page.
// TypeScript translation of `footerSection` from
// source/library/Scrod/Convert/ToHtml.hs (lines 250-263).

import type { Module } from "../types.js";
import { escapeHtml } from "./doc.js";

/**
 * Render the page footer with Scrod version information.
 */
export function renderFooter(module: Module): string {
  const version = module.version.join(".");
  return (
    `<footer class="mt-5 pt-3 border-top text-body-secondary small">` +
    `Generated by <a href="https://github.com/tfausak/scrod">Scrod</a>` +
    ` version ${escapeHtml(version)}` +
    `</footer>`
  );
}
