name: CI
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: cachix/install-nix-action@v30
      - run: mkdir artifact
      - run: nix-shell --run 'ghc-pkg list'
      - run: nix-shell --run 'cabal sdist --output-dir artifact'
      - run: nix-shell --run 'cabal configure --enable-documentation --enable-tests --flags=pedantic --haddock-for-hackage --jobs'
      - run: cat cabal.project.local
      - run: cp cabal.project.local artifact
      - run: nix-shell --run 'cabal update'
      - run: nix-shell --run 'cabal freeze'
      - run: cat cabal.project.freeze
      - run: cp cabal.project.freeze artifact
      - run: nix-shell --run 'cabal outdated --v2-freeze-file'
      - uses: actions/cache@v5
        with:
          key: ubuntu-${{ hashFiles('cabal.project.freeze') }}
          path: ~/.local/state/cabal
          restore-keys: ubuntu-
      - run: nix-shell --run 'cabal build --only-download'
      - run: nix-shell --run 'cabal build --only-dependencies'
      - run: nix-shell --run 'cabal build'
      - run: cp dist-newstyle/scrod-*-docs.tar.gz artifact
      - run: cp $( nix-shell --run 'cabal list-bin scrod' ) artifact
      - run: tar --create --file artifact.tar --verbose artifact
      - uses: actions/upload-artifact@v6
        with:
          name: scrod-${{ github.sha }}-ubuntu
          path: artifact.tar
      - run: nix-shell --run 'cabal run -- scrod-test-suite'
  cabal:
    name: Cabal
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: cachix/install-nix-action@v30
      - run: nix-shell --run 'cabal check'
  hlint:
    name: HLint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: cachix/install-nix-action@v30
      - run: nix-shell --run 'hlint .'
  ormolu:
    name: Ormolu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: cachix/install-nix-action@v30
      - run: nix-shell --run 'ormolu --mode check $(git ls-files "*.hs")'
