name: CI
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: cachix/install-nix-action@v30
        with:
          nix_path: nixpkgs=https://github.com/NixOS/nixpkgs/archive/871b9fd269ff6246794583ce4ee1031e1da71895.tar.gz
      - id: meta
        run: |
          echo name=$( grep ^name: *.cabal | cut -d ' ' -f 2 ) >> $GITHUB_OUTPUT
          echo version=$( grep ^version: *.cabal | cut -d ' ' -f 2 ) >> $GITHUB_OUTPUT
      - run: nix-shell --run 'cabal-gild --input ${{ steps.meta.outputs.name }}.cabal --mode check'
      - run: nix-shell --run 'cabal check'
      - run: nix-shell --run 'hlint .'
      - run: nix-shell --run 'ormolu --mode check $( git ls-files "*.hs" )'
      - run: mkdir artifact
      - run: nix-shell --run 'ghc-pkg list'
      - run: nix-shell --run 'cabal sdist --output-dir artifact'
      - run: nix-shell --run 'cabal configure --enable-documentation --enable-tests --flags=pedantic --ghc-options=-fwrite-ide-info --haddock-for-hackage --jobs'
      - run: cat cabal.project.local
      - run: cp cabal.project.local artifact
      - run: nix-shell --run 'cabal update'
      - run: nix-shell --run 'cabal freeze'
      - run: cat cabal.project.freeze
      - run: cp cabal.project.freeze artifact
      - run: nix-shell --run 'cabal outdated --v2-freeze-file'
      - uses: actions/cache@v5
        with:
          key: ${{ hashFiles('cabal.project.freeze') }}
          path: ~/.local/state/cabal
      - run: nix-shell --run 'cabal build --only-download'
      - run: nix-shell --run 'cabal build --only-dependencies'
      - run: nix-shell --run 'cabal build'
      - run: cp dist-newstyle/${{ steps.meta.outputs.name }}-${{ steps.meta.outputs.version }}-docs.tar.gz artifact
      - run: cp $( nix-shell --run 'cabal list-bin scrod' ) artifact
      - run: tar --create --file artifact.tar --verbose artifact
      - uses: actions/upload-artifact@v6
        with:
          name: scrod-${{ github.sha }}
          path: artifact.tar
      - run: nix-shell --run 'cabal run -- scrod-test-suite'
      - run: nix-shell --run weeder
