jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: mkdir artifact
      - id: haskell
        uses: haskell-actions/setup@v2
        with:
          ghc-version: '9.10'
      - run: cabal sdist --output-dir artifact
      - run: cabal configure --enable-tests --flags=pedantic
      - run: cat cabal.project.local
      - run: cp cabal.project.local artifact
      - run: cabal freeze
      - run: cat cabal.project.freeze
      - run: cp cabal.project.freeze artifact
      - run: cabal outdated --v2-freeze-file
      - uses: actions/cache@v4
        with:
          key: hashFiles('cabal.project.freeze')
          path: ${{ steps.haskell.outputs.cabal-store }}
      - run: cabal build --only-download
      - run: cabal build --only-dependencies
      - run: cabal build
      - run: tar --create --file artifact.tar --verbose artifact
      - uses: actions/upload-artifact@v4
        with:
          name: scrod-${{ github.sha }}
          path: artifact.tar
      - run: cabal test --test-options '--randomize --strict'
  cabal:
    name: Cabal
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: cabal check
  deploy:
    if: ${{ github.ref == 'refs/heads/main' }}
    name: Deploy
    needs: build
    secrets: inherit
    uses: ./.github/workflows/deploy.yml
  gild:
    name: Gild
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: tfausak/cabal-gild-setup-action@v2
      - run: cabal-gild --input scrod.cabal --mode check
  hlint:
    name: HLint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: haskell-actions/hlint-setup@v2
      - uses: haskell-actions/hlint-run@v2
        with:
          fail-on: status
  ormolu:
    name: Ormolu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: haskell-actions/run-ormolu@v16
name: CI
on:
  pull_request:
    branches:
      - main
  push: null
