name: CI
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}-latest
    steps:
      - uses: actions/checkout@v6
      - run: mkdir artifact
      - uses: haskell/ghcup-setup@v1
        with:
          ghc: "9.10"
          cabal: latest
      - run: ghc-pkg list
      - run: cabal sdist --output-dir artifact
      - run: cabal configure --enable-documentation --enable-tests --flags=pedantic --haddock-for-hackage --jobs
      - run: cat cabal.project.local
      - run: cp cabal.project.local artifact
      - run: cabal update
      - run: cabal freeze
      - run: cat cabal.project.freeze
      - run: cp cabal.project.freeze artifact
      - run: cabal outdated --v2-freeze-file
      - uses: actions/cache@v5
        with:
          key: ${{ matrix.os }}-${{ hashFiles('cabal.project.freeze') }}
          path: ~/.local/state/cabal
          restore-keys: ${{ matrix.os }}-
      - run: cabal build --only-download
      - run: cabal build --only-dependencies
      - run: cabal build
      - run: cp dist-newstyle/scrod-*-docs.tar.gz artifact
      - run: cp $( cabal list-bin scrod ) artifact
      - run: tar --create --file artifact.tar --verbose artifact
      - uses: actions/upload-artifact@v6
        with:
          name: scrod-${{ github.sha }}-${{ matrix.os }}
          path: artifact.tar
      - run: cabal run -- scrod-test-suite
    strategy:
      matrix:
        include:
          - os: macos
          - os: ubuntu
          - os: windows
  cabal:
    name: Cabal
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - run: cabal check
  hlint:
    name: HLint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: haskell-actions/hlint-setup@v2
      - uses: haskell-actions/hlint-run@v2
        with:
          fail-on: status
  ormolu:
    name: Ormolu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: haskell-actions/run-ormolu@v17
