concurrency: deploy
jobs:
  deploy:
    environment: production
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: flyctl deploy --image ghcr.io/tfausak/scrod:sha-${{ github.sha }}
name: Deploy
on:
  workflow_call:
    secrets:
      FLY_API_TOKEN:
        required: true
  workflow_dispatch: null
